import test from 'node:test';
import assert from 'node:assert/strict';
import { GameModel, randomSource, makeRow, obstacleShape, swipeAction, LANES } from '../lib/game/model.mjs';
const advance=(g,seconds)=>{for(let t=0;t<seconds;t+=1/120)g.step(1/120);};
function clean(){const g=new GameModel();g.start();g.items=[];g.nextRow=1e9;return g;}
test('run, input, jump, fast fall and slide are responsive',()=>{const g=clean();advance(g,1);assert(g.distance>15&&g.score>150);g.action('left');advance(g,.15);assert.equal(g.lane,0);assert(g.x<-2.5);g.action('right');g.action('right');advance(g,.2);assert(g.x>2.5);g.action('jump');advance(g,.25);assert(g.y>1.7);g.action('slide');advance(g,.3);assert.equal(g.y,0);g.action('slide');assert(g.slide>0);advance(g,1);assert.equal(g.slide,0);});
test('pause freezes distance, jumping, timer, and score; restart resets run',()=>{const g=clean();g.action('jump');g.magnet=8;advance(g,.1);g.action('pause');const before=g.snapshot(),y=g.y;advance(g,8);assert.deepEqual(g.snapshot(),before);assert.equal(g.y,y);g.action('resume');advance(g,.1);assert(g.distance>before.distance);g.action('restart');assert.equal(g.score,0);assert.equal(g.distance,0);assert.equal(g.state,'PLAYING');g.action('menu');assert.equal(g.state,'MENU');});
test('physical collision, jump clearance, slide clearance, shield and game over',()=>{for(const mode of ['none','jump','slide','shield']){const g=clean(),type=mode==='slide'?'arch':'low';g.add({kind:'obstacle',type,lane:1,d:5,y:0,...obstacleShape(type)});if(mode==='jump')g.action('jump');if(mode==='slide')g.action('slide');if(mode==='shield')g.shield=1;advance(g,.5);assert.equal(g.state,mode==='none'?'DYING':'PLAYING',mode);if(mode==='shield')assert.equal(g.shield,0);if(mode==='none'){g.finishDeath(1);assert.equal(g.state,'GAMEOVER');}}});
test('standing hits arch and lane switch avoids tall vehicle',()=>{let g=clean();g.add({kind:'obstacle',type:'arch',lane:1,d:5,y:0,...obstacleShape('arch')});advance(g,.5);assert.equal(g.state,'DYING');g=clean();g.add({kind:'obstacle',type:'bus',lane:1,d:12,y:0,...obstacleShape('bus')});g.action('left');advance(g,1);assert.equal(g.state,'PLAYING');});
test('all collectibles and durable best score',()=>{const data=new Map(),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};const g=new GameModel({storage});g.start();g.items=[];g.nextRow=1e9;for(const kind of ['magnet','shield','multiplier']){g.add({kind,lane:1,d:g.distance+1,y:1});advance(g,.1);assert(g[kind]>0);}g.add({kind:'coin',lane:0,d:g.distance+5,y:2.5});advance(g,.05);assert.equal(g.coins,2);g.die();const reloaded=new GameModel({storage});assert.equal(reloaded.best,g.score);assert(reloaded.best>0);const denied=new GameModel({storage:{getItem(){throw Error('denied')},setItem(){throw Error('denied')}}});denied.start();denied.die();});
test('swipes map all directions and discard taps',()=>{assert.equal(swipeAction(-80,4),'left');assert.equal(swipeAction(80,4),'right');assert.equal(swipeAction(4,-80),'jump');assert.equal(swipeAction(4,80),'slide');assert.equal(swipeAction(4,8),null);});
test('100,000 procedural rows always leave a reachable clear lane',()=>{let d=80,safe=1;const rng=randomSource(987);for(let i=0;i<100000;i++){const row=makeRow(d,safe,rng,i);assert(row.obstacles.length>=1&&row.obstacles.length<=2);assert(!row.obstacles.some(o=>o.lane===row.safe));assert(Math.abs(row.safe-safe)<=1);assert.equal(new Set(row.obstacles.map(o=>o.lane)).size,row.obstacles.length);const v=Math.min(35,16+d/180);assert((row.gap-10)/v>1.1);safe=row.safe;d+=row.gap;}});
test('100 km run via guaranteed safe path remains playable and memory bounded',()=>{const g=new GameModel({seed:726});g.start();let maxItems=0,maxRows=0;while(g.distance<100000){const row=g.rows.find(r=>r.d>g.distance-5);if(row){g.lane=row.safe;g.x=LANES[row.safe];}g.step(.05);assert.equal(g.state,'PLAYING',`failed at ${g.distance}`);maxItems=Math.max(maxItems,g.items.length);maxRows=Math.max(maxRows,g.rows.length);g.consumeEvents();}assert(g.speed===35);assert(maxItems<100);assert(maxRows<10);console.log({distance:g.distance,maxItems,maxRows,speed:g.speed});});
